### ISSUE TITLE
Command not working as expected

### ISSUE THREAD

**Issue by filiphagan** [DavidAnson/markdownlint-cli2-action#10]
After adding `command: config` to my workflow markdownlint-cli2 doesn't find any Markdown files in the directory

Current setup in `ci.yml`:
```
- name: Lint all Markdown files
  uses: DavidAnson/markdownlint-cli2-action@0820d56e6c53c3cc344ec2ef9c09fc74041aeb1c
    with:
      command: config
      globs: |
        "./.github/workflows/config/.markdownlint.yml"
        "**/*.md"
```

Current output:
```
> Run DavidAnson/markdownlint-cli2-action@0820d56e6c53c3cc344ec2ef9c09fc74041aeb1c
markdownlint-cli2-config v0.4.0 (markdownlint v0.25.1)
Finding: "**/*.md"
Linting: 0 file(s)
Summary: 0 error(s)
```

Expected output:
```
> Run DavidAnson/markdownlint-cli2-action@0820d56e6c53c3cc344ec2ef9c09fc74041aeb1c
markdownlint-cli2-config v0.4.0 (markdownlint v0.25.1)
Finding: "**/*.md"
Linting: 25 file(s)
Summary: 0 error(s)
```

Previous setup returning expected output:
```
- name: Copy markdown config file to root
  run: |
    cp ./.github/workflows/config/.markdownlint.yml .markdownlint.yml
- name: Lint all Markdown files
  uses: DavidAnson/markdownlint-cli2-action@v5
    with:
      globs: "**/*.md"
```
