### ISSUE TITLE
Question: Config for `markdownlint-cli2-action` vs `markdownlint-cli2`

### ISSUE THREAD

**Issue by hguturu** [DavidAnson/markdownlint-cli2-action#254]
I was wondering if the default config for the action is different from the cli tool.

I have a pre-commit setup for  `markdownlint-cli2`.
```yaml
-   repo: https://github.com/DavidAnson/markdownlint-cli2
    rev: v0.17.2
    hooks:
    -   id: markdownlint-cli2
        args: [--fix]
```
In addition in the root of the repo, I have `.markdownlint.yaml`
```yaml
# Default state for all rules
default: true

# MD013/line-length : Line length : https://github.com/DavidAnson/markdownlint/blob/v0.32.1/doc/md013.md
MD013:
  # Number of characters
  line_length: 120
```
and `.markdownlint-cli2.yaml`
```yaml
# Define glob expressions to use (only valid at root)
globs:
  - "**/*.qmd"
 ```

When I run the pre-commits, the only lint errors I get are `MD013` and `MD045` related.

But, when I run the action with 
```yaml
  markdown-ruff-mypy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: DavidAnson/markdownlint-cli2-action@v19
```

I get lint errors for `MD013`, `MD045`, but also `MD009`, `MD012`, `MD031`, `MD032`. I am fine with the stricter linting, but I would like to be able to configure the actions and pre-commits to behave the same.

I believe the configs are difference since the actions intial output is
```
Run DavidAnson/markdownlint-cli2-action@v19
  with:
    globs: *.{md,markdown}
    separator: 
  
markdownlint-cli2 v0.17.2 (markdownlint v0.37.4)
Finding: *.{md,markdown} **/*.qmd
Linting: 11 file(s)
Summary: 56 error(s)
``` 
, while the pre-commit output is
```
markdownlint-cli2 v0.17.2 (markdownlint v0.37.4)
Finding: README.md **/*.qmd
Linting: 11 file(s)
Summary: 38 error(s)
```
**Note:** The error differences are not due to the globs picking up different files. The same file is getting different lint errors in the two cases.

*Unrelated Question:* I noticed most of the examples use the glob `*.{md,markdown}`, but when I try to do `*.qmd` it doesn't work and I have to use `**/*.qmd`.
