### ISSUE TITLE
Expose -fix (and -config?) functionality via action

### ISSUE THREAD

**Issue by hatamiarash7** [DavidAnson/markdownlint-cli2-action#8]
Is there anything ti use `fix` option from [markdownlint-cli2](https://github.com/DavidAnson/markdownlint-cli2#markdownlint-cli2jsonc) ???  
I want then Action check & fix my codes in the same commit. Something like the one in [Prettier Action](https://github.com/marketplace/actions/prettier-action)

```yaml
- name: Prettify code
  uses: creyD/prettier_action@v4.2
  with:
    prettier_options: --write **/*.md
    only_changed: True
    same_commit: True
```

I don't want a simple `markdownlint-cli2 "**/*.md"` command. We need `markdownlint-cli2-fix "**/*.md"` here ( Using CLI command, config option, etc )

**Note:** I Don't want to put a `.markdownlint-cli2.jsonc` in every repository like this :

```jsonc
{
  "fix": true
}

```
